### ISSUE TITLE
Missing requirement `league/container`

### ISSUE THREAD

**Issue by tangrufus** [thanks-to-it/wp-dich#1]
`\League\Container\Container` is used in https://github.com/thanks-to-it/wp-dich/blob/02d12dd6d622eaee9a76c2376c3dedf33f7f2fb9/src/class-league-container-dic.php#L23 but `league/container` is missing from [`composer.json`](https://github.com/thanks-to-it/wp-dich/blob/02d12dd6d622eaee9a76c2376c3dedf33f7f2fb9/composer.json)

**Comment by pablo-sg-pacheco** [comment]
That's true. It's because the `League\Container` is just an optional DI Container. You can use it if you want but you are free to use the one you like.

Anyway I've added a very small DI Container on WP_DICH for basic stuff:
https://github.com/thanks-to-it/wp-dich/blob/master/src/class-dic.php

Thanks for taking a look at it! I really appreciate it!

**Comment by pablo-sg-pacheco** [comment]
I'll close the issue @TangRufus but if you noticed something I didn't realize let me know.
See you
